Repository contane/foreman, pull requests merged in 2024-07, with the labels that each got.

#20 chore: Configure ESLint
  .eslintrc.yml
  backend/.eslintrc.yml
  backend/package.json
  frontend/.eslintrc.yml
  frontend/package.json
  package-lock.json
  package.json
Labels: type::chore

#22 chore: Set up unit testing
  .github/workflows/test.yml
  backend/package.json
  backend/test/util/mutex.test.ts
  package-lock.json
  package.json
  test/config.test.ts
Labels: type::chore

#24 fix: Avoid page flickering on pod completion
  frontend/src/api/subscription.ts
Labels: type::fix

#28 chore: Create .github/CODEOWNERS
  .github/CODEOWNERS
Labels: type::chore

#26 chore: Publish README to Docker Hub
  .github/workflows/publish.yml
Labels: type::chore

#27 chore: Rename "Lint" workflow to "Lint and Test"
  .github/workflows/test.yml
Labels: type::chore

#29 feat: Show a message when the job list is empty
  frontend/src/pages/Jobs.tsx
Labels: type::feat

#32 docs: Add README sections for Kubernetes and Docker installation
  README.md
Labels: type::docs

#35 feat: Use consistent design for card components
  frontend/src/components/Card.tsx
  frontend/src/components/InfoCard.tsx
  frontend/src/components/JobPanel.tsx
  frontend/src/components/Label.tsx
  frontend/src/components/LinkCard.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Job.tsx
  frontend/src/pages/Jobs.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Trigger.tsx
Labels: type::feat

#38 fix: Use distinct icons for "status dot"
  frontend/src/components/StatusDot.tsx
  frontend/src/pages/Job.tsx
Labels: type::fix

#37 feat: Verify job ownership
  backend/src/api/jobs.ts
  backend/src/controllers/job.ts
  backend/src/controllers/trigger.ts
  backend/src/kubernetes/api.ts
  backend/src/metadata.ts
Labels: type::feat

#39 test: Add unit tests for prettifyLogs
  backend/src/api/pod-logs.ts
  backend/src/renovate/prettify-logs.ts
  backend/test/renovate/prettify-logs.test.ts
Labels: type::test

#40 fix: Refactor progress extraction and add tests
  backend/src/api/pod-progress.ts
  backend/src/renovate/progress.ts
  backend/test/renovate/progress.test.ts
Labels: type::fix

#41 test: Add cache unit tests
  backend/test/util/cache.test.ts
Labels: type::test

#44 fix: Set fixed height for LogDialog
  frontend/src/components/LogDialog.tsx
Labels: type::fix

#43 feat: Handle CronJob not found
  backend/src/api/cronjob.ts
  backend/src/kubernetes/api.ts
  frontend/src/components/InfoCard.tsx
  frontend/src/components/Navigation.tsx
  frontend/src/pages/Home.tsx
Labels: type::feat

#45 feat: Handle empty repository autodiscovery
  backend/src/api/pod-progress.ts
  frontend/src/pages/Job.tsx
Labels: type::feat

#49 chore(repo): Lint PR title
  .github/workflows/pr-lint.yml
Labels: type::chore

#47 chore(repo): Configure Renovate lockFileMaintenance
  renovate.json
Labels: type::chore

#48 chore(repo): Add GitHub Issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
Labels: type::chore

#50 fix: Skip parsing irrelevant log lines for progress
  backend/src/renovate/progress.ts
Labels: type::fix

#51 chore: Remove initial heading from PR template
  .github/pull_request_template.md
Labels: type::chore

#53 fix: Serialize access to pod logs
  backend/src/api/pod-logs.ts
  backend/src/controllers/logs.ts
Labels: type::fix

#61 test: Add tests for KubernetesApi
  backend/test/kubernetes/api.test.ts
Labels: type::test

#64 test: Add tests for authentication strategies
  backend/test/auth/local-strategy.test.ts
  backend/test/auth/oidc-strategy.test.ts
Labels: type::test

#65 feat: Handle termination signals
  Dockerfile
  package.json
  src/main.ts
  src/server.ts
Labels: type::feat

#66 test: Set up integration testing
  integration/backend/trigger.test.ts
  integration/fixtures.ts
  integration/frontend.test.ts
  package.json
  tsconfig.lint.json
Labels: type::test

#68 test: Add integration tests for local login
  integration/backend/auth/local.test.ts
  integration/backend/auth/logout.test.ts
  integration/backend/auth/me.test.ts
  integration/backend/auth/strategies.test.ts
  integration/fixtures.ts
Labels: type::test
